version: "3"
services:
  springboot-app:
    image: soumayaabderahmen/springboot-app
    build: ./IronByteIntern
    ports:
      - 8060:8060
    networks:
      - networkmysql
    volumes:
      - mysql-data:/var/lib/mysql
    depends_on:
      - mysqldb  # Ajouté
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: ironbyte  # Ajouté # Utilisé par Spring Boot

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3308:3306
    networks:
      - networkmysql
    environment:
      MYSQL_DATABASE: ironbyte # Utilisé lors de l'initialisation de MySQL
      MYSQL_ROOT_PASSWORD: root

  angular:
    image: soumayaabderahmen/ironbytepipeline-angular
    build: ./IronByte
    ports:
      - "4200:80"
    networks:
      - networkmysql

networks:
  networkmysql:
    driver: bridge

volumes:
  mysql-data: