apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-angular
  template:
    metadata:
      labels:
        app: frontend-angular
    spec:  
      containers:
        - name: ironbytepipeline-angular-1
          image: soumayaabderahmen/ironbytepipeline-angular	  # Mettez à jour avec le nom correct de votre image Angular
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: jenkins
spec:
  selector:
    app: frontend-angular
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
